name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: 22
  PNPM_VERSION: 10

jobs:
  test:
    name: Quality (Lint, Type Check, Test, Build)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run linting (Biome)
        run: pnpm lint
      - name: Check formatting (Biome)
        run: pnpm format:check || (echo 'Formatting issues found. Run pnpm format to fix.' && exit 1)
      - name: Run type checking
        run: pnpm type-check
      - name: Run tests with coverage
        run: pnpm test -- --coverage
      - name: Build packages
        run: pnpm build

  changeset-version:
    name: Version & Publish (GitHub Packages)
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Version & Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm version-packages
          commit: "chore: version packages"
          title: "chore: version packages"
          publish: pnpm release:github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
